### ISSUE TITLE
Heartbeat implementation

### ISSUE THREAD

**Issue by Supergiovane** [bartbutenaers/node-red-contrib-sse-client#4]
Hi Bart
first of all, ***thank you for this awesome node***.  I've starred your node.

I currently use it for receiving events from my Philips Hue Hub.
When the Philips Hub losts power or remains disconnected for more than 30 seconds, the SSE-Client ceases to receive the events, without emitting any error msg.
It **could be useful to have an URL to be "pinged" as heartbeat. If the URL cannot be reached for 1 or 2 times, SSE-Client should either automatically reconnect or send an error msg.**
The "Restart connection after timeout" option only works if you unplug the cable from the PC running nodered (so whenever the eth interface is down), otherwise unfortunately it does not work.

**Comment by bartbutenaers** [comment]
Hi @Supergiovane,

Unfortunately I cannot test this (I think at first sight), because I don't use this node myself.  I developed it solely to help some users in the community...

I am a bit surprised that the *"Restart connection after timeout"* option only works when you unplug the cat cable, but not when the hub goes down.  I would expect that it should also work in that case.  Smells more like a bug.

So I would like to determine whether I can fix this, instead of adding a heartbeat.  If you have any ideas about how I could reconstruct this problem here, please share it.  

Bart

**Comment by Supergiovane** [comment]
Hi Bart
I'm also a NodeRed dev (https://github.com/Supergiovane?tab=repositories) 
If this is not a problem for you, i could do a pull request for that. **I'm well aware** of the differences between your **SSE** node and the original **eventsource** code and i've read your discussions with the dev of **eventsource** about the "*".

**Comment by bartbutenaers** [comment]
Evening @Supergiovane,
That is quite some time ago that someone offered me to assist with a PR :-)
Thanks for that !!!!

What bothers me is that we the timeout handler is only called when you unplug the cable, but not when the hub is down.  I would expect the handler to be called in both cases?  So I have the impression that for some reason the timeout counter is ***not started*** in the latter case?  Does this make sense to you?

Is it possible for you to try debugging why this happens?  Because if there is a bug in the current code, I would prefer to fix this before we start adding new code for heartbeats.

**Comment by Supergiovane** [comment]
Hi Bart
Yes i’m looking for that “timeout” as well but….
As the timeout doesn’t work, i’ve put an inject node running every xx seconds, that restarts the sse.  This has solved the issue but… there is a memory leak. 
Every time you start the node via msg input, the used memory increases. I think there is something in the “eventsource” itself, because your code seems fine. 
I’m looking into that first, because the garbage collector is unable to free the memory. 
I’ll keep you informed.

**Comment by bartbutenaers** [comment]
Awesome!!!  Thanks for the help!!

**Comment by Supergiovane** [comment]
Hi Bart
The PR is done.
I've changed nothing but the timeout and a little fix for mem leak.
Again, thank you for your work! I'm using it extensively!
Cheers from Italy.
